INSERT INTO Team (TeamID, Name, Country) VALUES
(1, "Liverpool", "England"),
(2, "Manchester City", "England"),
(3, "Leicester City", "England"),
(4, "Chelsea", "England"),
(5, "Manchester United", "England"),
(6, "Wolverhampton Wanderers", "England"),
(7, "Sheffield United", "England"),
(8, "Tottenham Hotspur", "England"),
(9, "Arsenal", "England"),
(10, "Burnley", "England"),
(11, "Crystal Palace", "England"),
(12, "Everton", "England"),
(13, "Newcastle United", "England"),
(14, "Southampton", "England"),
(15, "Brighton & Hove Albion", "England"),
(16, "West Ham United", "England"),
(17, "Watford", "England"),
(18, "Bournemouth", "England"),
(19, "Aston Villa", "England"),
(20, "Norwich City", "England"),
(21, "Barcelona", "Spain"),
(22, "Real Madrid", "Spain"),
(23, "Sevilla", "Spain"),
(24, "Real Sociedad", "Spain"),
(25, "Getafe", "Spain"),
(26, "Atlético Madrid", "Spain"),
(27, "Valencia", "Spain"),
(28, "Villarreal", "Spain"),
(29, "Granada", "Spain"),
(30, "Athletic Bilbao", "Spain"),
(31, "Osasuna", "Spain"),
(32, "Real Betis", "Spain"),
(33, "Levante", "Spain"),
(34, "Alavés", "Spain"),
(35, "Valladolid", "Spain"),
(36, "Eibar", "Spain"),
(37, "Celta Vigo", "Spain"),
(38, "Mallorca", "Spain"),
(39, "Bayern Munich", "Germany"),
(40, "Borussia Dortmund", "Germany"),
(41, "Bayer Leverkusen", "Germany"),
(42, "RB Leipzig", "Germany"),
(43, "Borussia Mönchengladbach", "Germany"),
(44, "VfL Wolfsburg", "Germany"),
(45, "1899 Hoffenheim", "Germany"),
(46, "SC Freiburg", "Germany"),
(47, "Schalke 04", "Germany"),
(48, "Hertha BSC", "Germany"),
(49, "1. FC Köln", "Germany"),
(50, "FC Augsburg", "Germany"),
(51, "Union Berlin", "Germany"),
(52, "Eintracht Frankfurt", "Germany"),
(53, "Mainz 05", "Germany"),
(54, "Fortuna Düsseldorf", "Germany"),
(55, "Werder Bremen", "Germany"),
(56, "SC Paderborn", "Germany"),
(57, "Besa", "Albania"),
(58, "Besëlidhja", "Albania"),
(59, "Burreli", "Albania"),
(60, "Dinamo Tirana", "Albania"),
(61, "Erzeni", "Albania"),
(62, "Egnatia", "Albania"),
(63, "Korabi", "Albania"),
(64, "Veleçiku", "Albania"),
(65, "Vllaznia", "Albania"),
(66, "Vora", "Albania"),
(67, "Apolonia", "Albania"),
(68, "Bylis", "Albania"),
(69, "Elbasani", "Albania"),
(70, "Iliria", "Albania"),
(71, "Lushnja", "Albania"),
(72, "Oriku", "Albania"),
(73, "Pogradeci", "Albania"),
(74, "Shënkolli", "Albania"),
(75, "Tomori", "Albania"),
(76, "Turbina", "Albania"),
(77, "Inter Club d'Escaldes", "Andorra"),
(78, "FC Santa Coloma", "Andorra"),
(79, "Engordany", "Andorra"),
(80, "Sant Juli?", "Andorra"),
(81, "UE Santa Coloma", "Andorra"),
(82, "Atl?tic Club d'Escaldes", "Andorra"),
(83, "Ordino", "Andorra"),
(84, "Carroi", "Andorra"),
(85, "Ararat-Armenia", "Armenia"),
(86, "Lori", "Armenia"),
(87, "Alashkert", "Armenia"),
(88, "Ararat", "Armenia"),
(89, "Noah", "Armenia"),
(90, "Shirak", "Armenia"),
(91, "Pyunik", "Armenia"),
(92, "Urartu", "Armenia"),
(93, "Gandzasar", "Armenia"),
(94, "Yerevan", "Armenia"),
(95, "LASK", "Austria"),
(96, "Red Bull Salzburg", "Austria"),
(97, "Rapid Wien", "Austria"),
(98, "Wolfsberg", "Austria"),
(99, "Sturm Graz", "Austria"),
(100, "Hartberg", "Austria"),
(101, "Austria Wien", "Austria"),
(102, "Rheindorf Altach", "Austria"),
(103, "Admira Wacker Mödling", "Austria"),
(104, "WSG Tirol", "Austria"),
(105, "Mattersburg", "Austria"),
(106, "St. Pölten", "Austria"),
(107, "Dynamo Brest", "Belarus"),
(108, "BATE Borisov", "Belarus"),
(109, "Shakhtyor Soligorsk", "Belarus"),
(110, "Dinamo Minsk", "Belarus"),
(111, "Isloch Minsk Raion", "Belarus"),
(112, "Torpedo-BelAZ Zhodino", "Belarus"),
(113, "Gorodeya", "Belarus"),
(114, "Slavia Mozyr", "Belarus"),
(115, "Minsk", "Belarus"),
(116, "Neman Grodno", "Belarus"),
(117, "Slutsk", "Belarus"),
(118, "Energetik-BGU Minsk", "Belarus"),
(119, "Vitebsk", "Belarus"),
(120, "Dnyapro Mogilev (R)", "Belarus"),
(121, "Gomel", "Belarus"),
(122, "Torpedo Minsk", "Belarus"),
(123, "Club Brugge", "Belgium"),
(124, "Gent", "Belgium"),
(125, "Charleroi", "Belgium"),
(126, "Antwerp", "Belgium"),
(127, "Standard Li?ge", "Belgium"),
(128, "Mechelen", "Belgium"),
(129, "Genk", "Belgium"),
(130, "Anderlecht", "Belgium"),
(131, "Zulte Waregem", "Belgium"),
(132, "Excel Mouscron", "Belgium"),
(133, "Kortrijk", "Belgium"),
(134, "Sint-Truiden", "Belgium"),
(135, "Eupen", "Belgium"),
(136, "Cercle Brugge", "Belgium"),
(137, "Oostende", "Belgium"),
(138, "Waasland-Beveren", "Belgium"),
(139, "Ludogorets", "Bulgaria"),
(140, "Levski Sofia", "Bulgaria"),
(141, "Lokomotiv Plovdiv", "Bulgaria"),
(142, "CSKA Sofia", "Bulgaria"),
(143, "Slavia Sofia", "Bulgaria"),
(144, "Cherno More", "Bulgaria"),
(145, "Beroe", "Bulgaria"),
(146, "Botev Plovdiv", "Bulgaria"),
(147, "Arda", "Bulgaria"),
(148, "Etar", "Bulgaria"),
(149, "Tsarsko Selo", "Bulgaria"),
(150, "Botev Vratsa", "Bulgaria"),
(151, "Dunav Ruse", "Bulgaria"),
(152, "Vitosha Bistritsa", "Bulgaria"),
(153, "Dinamo Zagreb", "Croatia"),
(154, "Rijeka", "Croatia"),
(155, "Lokomotiva", "Croatia"),
(156, "Hajduk Split", "Croatia"),
(157, "Osijek", "Croatia"),
(158, "Gorica", "Croatia"),
(159, "Slaven Belupo", "Croatia"),
(160, "Istra 1961", "Croatia"),
(161, "Inter Zapresic", "Croatia"),
(162, "Varazdin", "Croatia"),
(163, "Omonia", "Cyprus"),
(164, "Anorthosis Famagusta", "Cyprus"),
(165, "APOEL", "Cyprus"),
(166, "Apollon Limassol", "Cyprus"),
(167, "AEK Larnaca", "Cyprus"),
(168, "AEL Limassol", "Cyprus"),
(169, "Pafos FC", "Cyprus"),
(170, "Nea Salamis Famagusta", "Cyprus"),
(171, "Olympiakos Nicosia", "Cyprus"),
(172, "Enosis Neon Paralimni", "Cyprus"),
(173, "Ethnikos Achna", "Cyprus"),
(174, "Doxa Katokopias", "Cyprus"),
(175, "Midtjylland", "Denmark"),
(176, "Copenhagen", "Denmark"),
(177, "Nordsj?lland", "Denmark"),
(178, "AGF", "Denmark"),
(179, "Br?ndby", "Denmark"),
(180, "AaB", "Denmark"),
(181, "Randers", "Denmark"),
(182, "Lyngby", "Denmark"),
(183, "OB.", "Denmark"),
(184, "Horsens", "Denmark"),
(185, "S?nderjyskE", "Denmark"),
(186, "Hobro", "Denmark"),
(187, "Esbjerg", "Denmark"),
(188, "Silkeborg", "Denmark"),
(189, "KuPS", "Finland"),
(190, "FC Inter", "Finland"),
(191, "FC Honka", "Finland"),
(192, "Ilves", "Finland"),
(193, "HJK", "Finland"),
(194, "IFK Mariehamn", "Finland"),
(195, "HIFK", "Finland"),
(196, "FC Lahti", "Finland"),
(197, "SJK", "Finland"),
(198, "RoPS", "Finland"),
(199, "KPV", "Finland"),
(200, "VPS", "Finland"),
(201, "Paris Saint-Germain", "France"),
(202, "Marseille", "France"),
(203, "Rennes", "France"),
(204, "Lille", "France"),
(205, "Nice", "France"),
(206, "Reims", "France"),
(207, "Lyon", "France"),
(208, "Montpellier", "France"),
(209, "Monaco", "France"),
(210, "Strasbourg", "France"),
(211, "Angers", "France"),
(212, "Bordeaux", "France"),
(213, "Nantes", "France"),
(214, "Brest", "France"),
(215, "Metz", "France"),
(216, "Dijon", "France"),
(217, "Saint-Étienne", "France"),
(218, "Nîmes", "France"),
(219, "Amiens", "France"),
(220, "Toulouse", "France"),
(221, "Dinamo Tbilisi", "Georgia"),
(222, "Dinamo Batumi", "Georgia"),
(223, "Saburtalo Tbilisi", "Georgia"),
(224, "Locomotive Tbilisi", "Georgia"),
(225, "Chikhura Sachkhere", "Georgia"),
(226, "Torpedo Kutaisi", "Georgia"),
(227, "Dila Gori", "Georgia"),
(228, "Rustavi", "Georgia"),
(229, "Sioni Bolnisi", "Georgia"),
(230, "WIT Georgia", "Georgia"),
(231, "Europa", "Gibraltar"),
(232, "St Joseph's", "Gibraltar"),
(233, "Lincoln Red Imps", "Gibraltar"),
(234, "Lynx", "Gibraltar"),
(235, "Bruno's Magpies", "Gibraltar"),
(236, "Lions Gibraltar", "Gibraltar"),
(237, "Mons Calpe", "Gibraltar"),
(238, "Europa Point", "Gibraltar"),
(239, "Manchester 62", "Gibraltar"),
(240, "Boca Gibraltar", "Gibraltar"),
(241, "Glacis United", "Gibraltar"),
(242, "College 1975", "Gibraltar"),
(243, "Olympiacos", "Greece"),
(244, "PAOK", "Greece"),
(245, "AEK Athens", "Greece"),
(246, "Panathinaikos", "Greece"),
(247, "OFI", "Greece"),
(248, "Aris", "Greece"),
(249, "Atromitos", "Greece"),
(250, "AEL", "Greece"),
(251, "Xanthi", "Greece"),
(252, "Asteras Tripolis", "Greece"),
(253, "Lamia", "Greece"),
(254, "Volos", "Greece"),
(255, "Panetolikos", "Greece"),
(256, "Panionios", "Greece"),
(257, "Maccabi Tel Aviv", "Israel"),
(258, "Maccabi Haifa", "Israel"),
(259, "Beitar Jerusalem", "Israel"),
(260, "Hapoel Be'er Sheva", "Israel"),
(261, "Hapoel Tel Aviv", "Israel"),
(262, "Hapoel Haifa", "Israel"),
(263, "Bnei Yehuda", "Israel"),
(264, "Hapoel Hadera", "Israel"),
(265, "Maccabi Netanya", "Israel"),
(266, "F.C. Ashdod", "Israel"),
(267, "Hapoel Kfar Saba", "Israel"),
(268, "Ironi Kiryat Shmona", "Israel"),
(269, "Sektzia Nes Tziona", "Israel"),
(270, "Hapoel Ra'anana", "Israel"),
(271, "Juventus", "Italy"),
(272, "Lazio", "Italy"),
(273, "Internazionale", "Italy"),
(274, "Atalanta", "Italy"),
(275, "Roma", "Italy"),
(276, "Napoli", "Italy"),
(277, "Milan", "Italy"),
(278, "Hellas Verona", "Italy"),
(279, "Parma", "Italy"),
(280, "Bologna", "Italy"),
(281, "Sassuolo", "Italy"),
(282, "Cagliari", "Italy"),
(283, "Fiorentina", "Italy"),
(284, "Udinese", "Italy"),
(285, "Torino", "Italy"),
(286, "Sampdoria", "Italy"),
(287, "Genoa", "Italy"),
(288, "Lecce", "Italy"),
(289, "SPAL", "Italy"),
(290, "Brescia", "Italy"),
(291, "Astana", "Kazakhstan"),
(292, "Kairat", "Kazakhstan"),
(293, "Ordabasy", "Kazakhstan"),
(294, "Tobol", "Kazakhstan"),
(295, "Zhetysu", "Kazakhstan"),
(296, "Kaisar", "Kazakhstan"),
(297, "Okzhetpes", "Kazakhstan"),
(298, "Irtysh Pavlodar", "Kazakhstan"),
(299, "Shakhter Karagandy", "Kazakhstan"),
(300, "Taraz", "Kazakhstan"),
(301, "Atyrau", "Kazakhstan"),
(302, "Aktobe", "Kazakhstan"),
(303, "Floriana", "Malta"),
(304, "Valletta", "Malta"),
(305, "Hibernians", "Malta"),
(306, "Sirens", "Malta"),
(307, "Birkirkara", "Malta"),
(308, "Gżira United", "Malta"),
(309, "Balzan", "Malta"),
(310, "Mosta", "Malta"),
(311, "Hamrun Spartans", "Malta"),
(312, "Sliema Wanderers", "Malta"),
(313, "Gudja United", "Malta"),
(314, "St. Lucia", "Malta"),
(315, "Senglea Athletic", "Malta"),
(316, "Tarxien Rainbows", "Malta"),
(317, "Sheriff Tiraspol", "Moldova"),
(318, "Sfintul Gheorghe", "Moldova"),
(319, "Petrocub-Hincesti", "Moldova"),
(320, "Dinamo-Auto", "Moldova"),
(321, "Milsami Orhei", "Moldova"),
(322, "Speranta Nisporeni", "Moldova"),
(323, "Zimbru Chisinau", "Moldova"),
(324, "Codru Lozova", "Moldova"),
(325, "Buducnost", "Montenegro"),
(326, "Sutjeska", "Montenegro"),
(327, "Iskra", "Montenegro"),
(328, "Rudar", "Montenegro"),
(329, "Zeta", "Montenegro"),
(330, "Podgorica", "Montenegro"),
(331, "Titograd", "Montenegro"),
(332, "Petrovac", "Montenegro"),
(333, "Kom", "Montenegro"),
(334, "Grbalj", "Montenegro"),
(335, "Ajax", "Netherlands"),
(336, "AZ", "Netherlands"),
(337, "Feyenoord", "Netherlands"),
(338, "PSV Eindhoven", "Netherlands"),
(339, "Willem II", "Netherlands"),
(340, "Utrecht", "Netherlands"),
(341, "Vitesse", "Netherlands"),
(342, "Heracles Almelo", "Netherlands"),
(343, "Groningen", "Netherlands"),
(344, "Heerenveen", "Netherlands"),
(345, "Sparta Rotterdam", "Netherlands"),
(346, "Emmen", "Netherlands"),
(347, "VVV-Venlo", "Netherlands"),
(348, "Twente", "Netherlands"),
(349, "PEC Zwolle", "Netherlands"),
(350, "Fortuna Sittard", "Netherlands"),
(351, "ADO Den Haag", "Netherlands"),
(352, "RKC Waalwijk", "Netherlands"),
(353, "Linfield", "Northern Ireland"),
(354, "Coleraine", "Northern Ireland"),
(355, "Crusaders", "Northern Ireland"),
(356, "Cliftonville", "Northern Ireland"),
(357, "Glentoran", "Northern Ireland"),
(358, "Larne", "Northern Ireland"),
(359, "Glenavon", "Northern Ireland"),
(360, "Carrick Rangers", "Northern Ireland"),
(361, "Dungannon Swifts", "Northern Ireland"),
(362, "Ballymena United", "Northern Ireland"),
(363, "Warrenpoint Town", "Northern Ireland"),
(364, "Institute", "Northern Ireland"),
(365, "Aalesund", "Norway"),
(366, "Bodo/Glimt", "Norway"),
(367, "Brann", "Norway"),
(368, "Haugesund", "Norway"),
(369, "Kristiansund", "Norway"),
(370, "Mjondalen", "Norway"),
(371, "Molde", "Norway"),
(372, "Odd", "Norway"),
(373, "Rosenborg", "Norway"),
(374, "Sandefjord", "Norway"),
(375, "Sarpsborg 08", "Norway"),
(376, "Stabaek", "Norway"),
(377, "Start", "Norway"),
(378, "Stromsgodset", "Norway"),
(379, "Valerenga", "Norway"),
(380, "Viking", "Norway"),
(381, "Legia Warsaw", "Poland"),
(382, "Slask Wrocław", "Poland"),
(383, "Piast Gliwice", "Poland"),
(384, "Cracovia", "Poland"),
(385, "Lech Poznan", "Poland"),
(386, "Pogon Szczecin", "Poland"),
(387, "Lechia Gdansk", "Poland"),
(388, "Rakow Czestochowa", "Poland"),
(389, "Jagiellonia Bialystok", "Poland"),
(390, "Zagłebie Lubin", "Poland"),
(391, "Wisla Płock", "Poland"),
(392, "Gornik Zabrze", "Poland"),
(393, "Wisla Krakow", "Poland"),
(394, "Korona Kielce", "Poland"),
(395, "Arka Gdynia", "Poland"),
(396, "LKS Lodz", "Poland"),
(397, "Zenit Saint Petersburg", "Russia"),
(398, "Lokomotiv Moscow", "Russia"),
(399, "Krasnodar", "Russia"),
(400, "Rostov", "Russia"),
(401, "CSKA Moscow", "Russia"),
(402, "Dynamo Moscow", "Russia"),
(403, "Arsenal Tula", "Russia"),
(404, "Spartak Moscow", "Russia"),
(405, "Ufa", "Russia"),
(406, "Ural Yekaterinburg", "Russia"),
(407, "Tambov", "Russia"),
(408, "Sochi", "Russia"),
(409, "Orenburg", "Russia"),
(410, "Rubin Kazan", "Russia"),
(411, "Krylia Sovetov Samara", "Russia"),
(412, "Akhmat Grozny", "Russia"),
(413, "Celtic", "Scotland"),
(414, "Rangers", "Scotland"),
(415, "Motherwell", "Scotland"),
(416, "Aberdeen", "Scotland"),
(417, "Livingston", "Scotland"),
(418, "St Johnstone", "Scotland"),
(419, "Hibernian", "Scotland"),
(420, "Kilmarnock", "Scotland"),
(421, "St Mirren", "Scotland"),
(422, "Ross County", "Scotland"),
(423, "Hamilton Academical", "Scotland"),
(424, "Heart of Midlothian", "Scotland"),
(425, "St. Gallen", "Switzerland"),
(426, "Young Boys", "Switzerland"),
(427, "Basel", "Switzerland"),
(428, "Servette", "Switzerland"),
(429, "Zürich", "Switzerland"),
(430, "Luzern", "Switzerland"),
(431, "Lugano", "Switzerland"),
(432, "Sion", "Switzerland"),
(433, "Neuchâtel Xamax", "Switzerland"),
(434, "Thun", "Switzerland"),
(435, "Shakhtar Donetsk", "Ukraine"),
(436, "Dynamo Kyiv", "Ukraine"),
(437, "Zorya Luhansk", "Ukraine"),
(438, "Desna Chernihiv", "Ukraine"),
(439, "FC Oleksandriya", "Ukraine"),
(440, "Kolos Kovalivka", "Ukraine"),
(441, "SC Dnipro-1", "Ukraine"),
(442, "FC Mariupol", "Ukraine"),
(443, "FC Lviv", "Ukraine"),
(444, "Vorskla Poltava", "Ukraine"),
(445, "Olimpik Donetsk", "Ukraine"),
(446, "Karpaty Lviv", "Ukraine"),
(447, "Connah's Quay Nomads", "Wales"),
(448, "The New Saints", "Wales"),
(449, "Bala Town", "Wales"),
(450, "Barry Town United", "Wales"),
(451, "Caernarfon Town", "Wales"),
(452, "Newtown", "Wales"),
(453, "Cardiff Metropolitan University", "Wales"),
(454, "Cefn Druids", "Wales"),
(455, "Aberystwyth Town", "Wales"),
(456, "Pen-y-Bont", "Wales"),
(457, "Carmarthen Town", "Wales"),
(458, "Airbus UK Broughton", "Wales"),
